import type { Metadata } from "next";

export const links = {
  sourceCode: "https://github.com/babamosie333",
  ownerName: "Vikram Singh",
  ownerEmail: "vikramsingh14052006@gmail.com",
  siteUrl: "https://novastack.vercel.app",
} as const;

export const siteConfig: Metadata = {
  metadataBase: new URL(links.siteUrl),
  title: `${links.ownerName}'s Portfolio`,
  description: "Modern & Minimalist Next.js Portfolio.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "aceternity",
    "aceternity-ui",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "modern-portfolio",
    "portfolio",
    "3d-portfolio",
    "animated-portfolio",
    "nextjs-portfolio",
    "react-portfolio",
    "react-three-fiber",
    "three.js",
    "animated-website",
    "framer",
    "framer-motion",
    "three",
    "react-icons",
    "lucide-react",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: [
    {
      name: links.ownerName,
      url: "https://github.com/babamosie333",
    },
  ],
  openGraph: {
    title: `${links.ownerName}'s Portfolio`,
    description: "Modern & Minimalist Next.js Portfolio.",
    url: links.siteUrl,
    siteName: `${links.ownerName}'s Portfolio`,
    images: [
      {
        url: "app/opengraph-image.png",
        width: 1200,
        height: 630,
        alt: `${links.ownerName}'s Portfolio Preview`,
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: `${links.ownerName}'s Portfolio`,
    description: "Modern & Minimalist Next.js Portfolio.",
    images: ["app/opengraph-image.png"],
  },
} as const;
